package util

type DeploymentConfig struct {
	Name                 string
	MasterVmSize         string
	NodeVmSize           string
	InitialNodeCount     int
	Username             string
	TenantID             string
	SubscriptionID       string
	ResourceGroup        string
	Location             string
	DeployerObjectID     string
	DeployerClientID     string
	DeployerClientSecret string
	ClientNames          []string
}

type AuthConfig struct {
}

type AppConfig struct {
	AppURL  string
	AppName string
}

type AppProperties struct {
	AppConfig
	ServicePrincipalObjectID    string
	ServicePrincipalFingerprint string
}

type VaultConfig struct {
	Name string
}

type VaultProperties struct {
	VaultConfig
	ServicePrincipalSecretURL string
}

type NetworkConfig struct {
	VnetCidr   string
	SubnetCidr string

	PodCidr     string
	ServiceCidr string

	MasterPrivateIp string
	ApiServiceIp    string
	DnsServiceIp    string
}

type NetworkProperties struct {
	NetworkConfig
}

type KubernetesConfig struct {
	HyperkubeContainerSpec string
}

type CloudConfigConfig struct {
	Master string
	Node   string
}

// appears in same order as in myriad variables
type DeploymentProperties struct {
	DeploymentConfig

	App         AppProperties
	Vault       VaultProperties
	Network     NetworkProperties
	CloudConfig CloudConfigConfig

	SshPublicKeyData string

	AutogeneratedClientNames []string
}

type ScaleConfig struct {
	NodeVmssName string
	NodeCount    int
}
