package util

type DeployConfigIn struct {
	DeploymentName              string
	OutputDirectory             string
	SubscriptionID              string
	TenantID                    string
	Location                    string
	ServicePrincipalCertificate string
	ServicePrincipalSecret      string
	ResourceGroup               string
	MasterVmSize                string
	NodeVmSize                  string
	NodeCount                   int
	Username                    string
	ClientID                    string
	ClientSecret                string
}

type DeployConfigOut struct {
	DeployConfigIn
	ServicePrincipalSecretURL   string
	SshPublicKeyData            string
	ServicePrincipalObjectID    string
	ServicePrincipalFingerprint string
	DeployerObjectID            string
	AppName                     string
	AppURL                      string
	VaultName                   string
	ClientNames                 []string
	AutogeneratedClientNames    []string
	MasterFqdn                  string
}
