package util

type DeployConfigIn struct {
	MasterVmSize         string
	NodeVmSize           string
	InitialNodeCount     int
	Username             string
	TenantID             string
	SubscriptionID       string
	ResourceGroup        string
	Location             string
	DeployerObjectID     string
	DeployerClientID     string
	DeployerClientSecret string
}

type AppConfig struct {
	TenantID                 string
	SubscriptionID           string
	ResourceGroup            string
	Location                 string
	AppURL                   string
	AppName                  string
	ServicePrincipalObjectID string
}

type VaultConfig struct {
	Name                        string
	ServicePrincipalSecretURL   string
	ServicePrincipalFingerprint string
}

type NetworkConfig struct {
	VnetCidr   string
	SubnetCidr string

	PodCidr     string
	ServiceCidr string

	MasterPrivateIp string
	ApiServiceIp    string
	DnsServiceIp    string
}

type KubernetesConfig struct {
	HyperkubeContainerSpec string
}

// appears in same order as in myriad variables
type Deployment struct {
	Name                 string
	MasterFqdn           string
	MasterVmSize         string
	NodeVmSize           string
	NodeVmssName         int
	NodeVmssInitialCount int
	Username             string

	App     AppConfig
	Vault   VaultConfig
	Network NetworkConfig

	SshPublicKeyData string

	ClientNames              []string
	AutogeneratedClientNames []string
}

type ScaleConfig struct {
	NodeVmssName string
	NodeCount    int
}

type VaultConfig struct {
	Name string
}

type CloudConfig struct {
	Master string
	Minion string
}
